#!/bin/bash
export POSIXLY_CORRECT=yes

function help(){
	

	echo " script usage:"
	echo "-------------------------------------------"
	echo " ./xtf [FILTER] [COMMAND] [USER_NAME] [LOG]"$'\n'"-------------------------------------------"
	echo " [FILTER] ->    after certain date '-a  <YYYY-MM-DD HH:MM:SS>'"
	echo "          ->   before certain date '-b' <YYYY-MM-DD HH:MM:SS>'"
	echo "          ->  only lines with currency '-c <code of currency>'"
	echo "----------------------------------------"
	echo " [COMMAND] -> 'list'/<blank> displays all logs of a trader "
	echo "           -> 'list-currency' displays currencies that were traded by a trader"
	echo "           -> 'status' displays status of currencies after all transaction "
	echo "           -> 'profit' displays status of currencies after certain profit"
	echo "----------------------------------------"
	echo " [USER_NAME] -> enter username, whose logs will be displayed"
	echo "             -> one name must be defined "
	echo "----------------------------------------"
	echo " [LOG]       -> enter '*.log' or '*.log.gz' containing all users data"
	echo "             -> one or more must be defined "
	echo "----------------------------------------"
	echo " "
	exit 0
 
}

function list(){
		
	echo "$2" | grep "$1"

}

function listcurrency(){
	
	all_curr=()
	while IFS= read -r line; do
		curr=$(echo "$line" | awk -F';' '{ print $3 }')
		all_curr+=("$curr")
	done < <(list "$1" "$2")
	
	printf "%s\n" "${all_curr[@]}" | sort -u 
}

function profit(){
	
	if ! [[ -v XTF_PROFIT ]]; then
		XTF_PROFIT=20
	fi

	mapfile -t stats < <(status "$1" "$2")

	for p in "${stats[@]}"; do
		num=$(echo "$p" | cut -d' ' -f3)
		curr=$(echo "$p" | cut -d' ' -f1)
		
		
		pr=$(echo "scale=2; $XTF_PROFIT / 100" | bc)

		if awk -v num="$num" 'BEGIN { if (num > 0) exit 0; else exit 1 }'; then
			num=$(awk -v num="$num" -v pr="$pr" 'BEGIN { result = num + num * pr; printf "%.4f", result }')
			echo "$curr : $num"
		else 
			echo "$curr : $num"	
		fi
	done
}


function status(){

	all_curr=()
	all_stats=()

	while IFS= read -r line; do

		curr=$(echo "$line" | cut -d';' -f3)
		stat=$(echo "$line" | cut -d';' -f3,4)
		
		all_curr+=("$curr")
		all_stats+=("$stat")
	done < <(echo "$2" | grep "$1")


	all_stats=($(for element in "${all_stats[@]}"; do echo "$element"; done | sort))
	all_curr=($(for element in "${all_curr[@]}"; do echo "$element"; done | sort))	

	results=()
	i=0
	j=0

	for c1 in "${all_curr[@]}"; do
		num1=$(echo "${all_stats[i]}" | cut -d';' -f2)
		
		j=0
		for c2 in "${all_curr[@]}"; do
			num2=$(echo "${all_stats[j]}" | cut -d';' -f2)
			

			if [ "$i" != "$j" ] && [ "$c1" == "$c2" ]; then
				num1=$(awk -v num1="$num1"  -v num2="$num2" 'BEGIN { sum = num1 + num2; printf "%.4f\n", sum }')
			fi
			
			((j++))
		done
		
		if [ "$i" == "$(echo "${#all_stats[@]}-1" | bc)" ]; then
			results+="$c1 : $num1"
		else
			results+="$c1 : "$num1""$'\n'
		fi		
			
		((i++))
	
	done

	echo "${results[@]}" | uniq


}

function after(){

	
	date=$(date -d "$1" +%s)
	while IFS= read -r line; do
			
		d=$(echo "$line" | awk -F';' '{ print $2 }')
		cmp_date=$(date -d "$d" +%s)
		

		if [[ "$cmp_date" -gt "$date" ]]; then
			echo "$line"
		fi				
	done < <(echo "$2")
}

function before(){

	date=$(date -d "$1" +%s)
	while IFS= read -r line; do
				
		d=$(echo "$line" | awk -F';' '{ print $2 }')
		cmp_date=$(date -d "$d" +%s)
		

		if [[ "$cmp_date" -lt "$date" ]]; then
			echo "$line"
		fi				
	done < <(echo "$2")

}
	

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	if [ $# == 1 ]; then 
		help
	else 
		echo "Unknown command" >&2
		exit 1
	fi
fi


is_file=0
num_of_names=0
num_of_filters=0
num_of_cmd=0

for arg in "$@"; do
		
	if [ "$arg" == "status" ] || [ "$arg" == "profit" ] || [ "$arg" == "list" ]; then
		cmd="$arg"
		((num_of_cmd++))
	elif [ "$arg" == "list-currency" ]; then
		cmd="listcurrency"
		((num_of_cmd++))
	
	elif [[ "$arg" == *.gz ]] && [[ "$is_file" == 0 ]]; then	
		file+=$(zcat "$arg")
		is_file=1
	elif [[ "$arg" == *.gz ]] && [[ "$is_file" == 1 ]]; then
		file+=$'\n'$(zcat "$arg")

	elif [[ "$arg" == *.log ]] && [[ "$is_file" == 0 ]]; then
		file+=$(cat "$arg")
		is_file=1	
	elif [[ "$arg" == *.log ]] && [[ "$is_file" == 1 ]]; then
		file+=$'\n'$(cat "$arg")

	elif [[ "$arg" =~ ^[[:alnum:]]{4,}$ ]]; then
		((num_of_names++))
		name="$arg"

	elif [[ "$arg" =~ ^[[:alnum:][:space:]]{4,}$ ]]; then  #kontrola aby v mene nebol biely znak
		echo "ERROR: invalid name" >&2
		exit 1
	fi
done

index=0
curr_filters=()
date_filters=()
dates=()
currencies=()


for arg in "$@"; do

	if [[ "$arg" =~ ^-a|-b$ ]]; then
		date_filters[$index]="$arg"
		i="$index"
		((num_of_filters++))
		((index++))

	elif [[ "$arg" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}[[:space:]][0-9]{2}:[0-9]{2}:[0-9]{2}$ ]] && [[ "$i" == "$(($index - 1))" ]]; then
		dates[$((index - 1))]="$arg"


	elif [[ "$arg" == "-c" ]]; then
		curr_filters[$index]="$arg"
		i="$index"
		((num_of_filters++))
		((index++))

	elif [[ "$arg" =~ ^[A-Z]{2,}$ ]] && [[ "$i" == "$(($index - 1))" ]]; then
		currencies[$((index - 1))]="$arg"
	

	
	fi	
done



if [[ "$is_file" == 0 ]] || [[ "$num_of_names" != 1 ]] || [[ "$num_of_cmd" -gt 1 ]]; then
	echo "ERROR: invalid number of key arguments" >&2
	exit 1
fi



if [[ "$num_of_cmd" == 1 ]]; then
	final_cmd="$cmd"	
else
	final_cmd="list"  # ak nie je zadany prikaz, pouzije sa 'list'
fi


if [[ "$num_of_filters" -ge 1 ]]; then  # ak su zadane filtre..

	index=0
	for f in "${date_filters[@]}"; do
			
		if [ "$f" == "-a" ]; then			
			file=$(after "${dates[$index]}" "$file")
		elif [ "$f" == "-b" ]; then
			file=$(before "${dates[$index]}" "$file")
		fi
		((index++))
	done
	

	if [[ "${#currencies[@]}" -gt 0 ]]; then

		index=0
		file2=""
		for c in "${currencies[@]}"; do

			d=$(echo "$file" | grep "$c")
			file2="$file2$d"
			file2="$file2"$'\n'
			((index++))
		done

		file="$file2"
		
	fi

	"$final_cmd" "$name" "$file"
else
	"$final_cmd" "$name" "$file"
fi
	



